In [2]:
import pandas as pd

In [9]:
# isin, between, str.contains, notna
# 0. 데이터 로딩
orders_df = pd.read_csv("../data/orders.csv", parse_dates=["order_datetime"])
order_items_df = pd.read_csv("../data/order_items.csv")
products_df = pd.read_csv("../data/products.csv")

In [ ]:
# 1. 데이터 탐색(구조, 결측, 기본 통계치)
# orders_df.head()
# orders_df.columns   
# 컬럼의 목록 출력 Index(['order_id', 'customer_id', 'order_datetime', 'channel', 'status'], dtype='str')

# orders_df.info()

# order_items_df.head()
# order_item_id	order_id	product_id	quantity	unit_price	discount

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

   order_item_id  order_id  product_id  quantity  unit_price  discount
0          59256    114625           3         1     20300.0      0.05
1         230587     66337          80         2     90000.0      0.45
2         279813    163343           3         3     20300.0      0.23
3          88487    180332          79         1      8600.0      0.38
4          39240    174179         232         1     42600.0      0.31

In [ ]:
# 2. isin([목록]) : 목록이 안에 있니? => return boolean
# channel (주문경로)확인 : 우리 회사의 상품이 어느 경로로 많이 팔리는지 확인
# orders_df["channel"].unique()     # ['store', 'web', 'app']
orders_df["channel"].value_counts() # 값('store', 'web', 'app')의 개수를 세라
# channel
# web      109958
# app       59894
# store     30148

# orders_df["channel"].value_counts()["web"]    # np.int64(109958)

# 두 개 값 한 번에 받아올 때는 isin()이 더 쉬움.(web+app 개수)
(orders_df["channel"].isin(["web","app"])).sum()

np.int64(169852)

In [26]:
# 취소, 반품 개수: status column => orders_df
# orders_df["status"].unique()
# ['delivered', 'canceled', 'paid', 'shipped', 'returned']
orders_df["status"].isin(["canceled","returned"]).sum()

np.int64(30014)

In [30]:
# 3. 주문 수량이 1개~3개 사이인 주문 건수
order_items_df["quantity"].between(1,3).sum()

np.int64(299692)

In [ ]:
# 4. 상품명에 "노트북" 포함된 상품의 개수.
# products_df.info()
products_df["product_name"].str.contains("노트북").sum()    # 노트북 포함 여부(boolean)

np.int64(18)

In [43]:
# 5. 주문 날짜/시간의 누락(결측, NaN, Na)된 행 찾아 개수 구하기
# orders_df["order_datetime"].isna().sum()
# 누락 안 된 개수
# orders_df.order_datetime.notna().sum()  # 대괄호연산자, . 둘 다 가능
# 행 찾기
con1 = orders_df["order_datetime"].isna()
orders_df[con1]

        order_id  customer_id order_datetime channel     status
40         44572         1763            NaT     web       paid
161       163116         1525            NaT     web       paid
195       196024         3906            NaT     web   returned
262       192106         1802            NaT     web  delivered
263       174676         2097            NaT     web    shipped
...          ...          ...            ...     ...        ...
199395    134760         3202            NaT     web  delivered
199552    114082         2087            NaT   store    shipped
199553    125945         1539            NaT     web   canceled
199851     93699         3003            NaT     app   returned
199878    131706         3904            NaT     web  delivered

[1933 rows x 5 columns]