In [2]:
import pandas as pd

products = pd.read_csv("../data/products.csv")

In [4]:
products.head(3)
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    int64
 1   product_name  500 non-null    str
 2   category      500 non-null    str
 3   price         500 non-null    str
 4   cost          500 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 35.5 KB

In [ ]:
products.describe()    # 기본 통계량
                       # head(), info(), describe() 시작 전에 데이터 구조 확인

       product_id           cost
count   500.00000     500.000000
mean    249.06200   30153.200000
std     143.80918   29877.242661
min       1.00000     400.000000
25%     124.75000    9800.000000
50%     249.50000   16950.000000
75%     373.25000   44425.000000
max     497.00000  165500.000000

In [ ]:
# 상품명, 코스트 column 추출
two_cols = products[["product_name", "cost"]]    # 컬럼이 두 개 추출 => return DataFrame
two_cols.head(2)

  product_name     cost
0       플러스 홍차   3700.0
1     프리미엄 노트북  28900.0

In [ ]:
# 주문 데이터 읽기
orders_df = pd.read_csv(
    "../data/orders.csv",           # order_datetime  str(datetime 아니라 str임)
    parse_dates=["order_datetime"]  # order_datetime의 dtype을 datetime64로 변경
)
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [ ]:
# 행 기준 추출 : loc[행,열] -> 문자열, iloc[행,열] -> 숫자
orders_df.loc[0:5]  # ':' => 범위 지정(행이 0이라는 값부터~5라는 값까지. 열은 없으니 모든 행.)
# orders_df.iloc[0:5]   # ':' => 범위 지정(행이 0~4행까지. start ~ end -1)

   order_id  customer_id      order_datetime channel     status
0     25463         1077 2024-06-25 00:17:41   store  delivered
1    171088         2998 2024-05-28 19:35:20     web  delivered
2     27437         4066 2024-02-14 17:49:14     app  delivered
3     98425         3243 2024-05-08 16:37:36   store  delivered
4     22325         5331 2024-04-17 20:08:22     app  delivered
5    104752         1160 2024-05-22 04:30:56     app   canceled

In [ ]:
# 행, 열 접근
print(orders_df.head())
print(orders_df.iloc[0,1])
print(orders_df.loc[0,"customer_id"])

   order_id  customer_id      order_datetime channel     status
0     25463         1077 2024-06-25 00:17:41   store  delivered
1    171088         2998 2024-05-28 19:35:20     web  delivered
2     27437         4066 2024-02-14 17:49:14     app  delivered
3     98425         3243 2024-05-08 16:37:36   store  delivered
4     22325         5331 2024-04-17 20:08:22     app  delivered
1077
1077

In [25]:
# 행, 열 접근
# 고객 정보
customer_df = pd.read_csv("../data/customers.csv")
print(customer_df.head())
print(customer_df.iloc[0,1])

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com
권준서

In [ ]:
# 앞에서 3행, 이름과 도시 추출
# customer_df.iloc[:3, [1,5]]           # 숫자로 추출(iloc)
customer_df.loc[:2, ["name","city"]]    # 숫자와 문자열 추출(loc)

  name city
0  권준서   부산
1  박준선   서울
2  전영경   인천

In [ ]:
# name, city 컬럼만 선택, 행 x
customer_df[["name","city"]].head()    # return DataFrame

  name city
0  권준서   부산
1  박준선   서울
2  전영경   인천
3  한재하   서울
4  송준연   대전