In [1]:
import pandas as pd

products_df = pd.read_csv("../data/products.csv")

In [2]:
products_df.head()

   product_id product_name category    price     cost
0         119       플러스 홍차       식품        0   3700.0
1          95     프리미엄 노트북       전자  68600.0  28900.0
2         112    프리미엄 원두커피       식품  10500.0   4700.0
3         164      베이직 마우스       전자  52100.0  32600.0
4         274       베이직 홍차      식품   16000.0  10500.0

In [ ]:
# 원가가 높은 상품의 이름과 카테고리 추출, cost > 100000 이상
products_df["cost"] > 100000    # Boolean (True, False) return Series

0      False
1      False
2      False
3      False
4      False
       ...
495     True
496    False
497    False
498    False
499    False
Name: cost, Length: 500, dtype: bool

In [13]:
expensive = products_df.loc[
    products_df['cost'] > 100000,           # 행 자리
    ["product_name", "category", "cost"]    # 열 자리, 다중 열 선택 => 데이터프레임(DataFrame) 추출
]

In [14]:
expensive.head()

   product_name category      cost
16       베이직 책상       가구  104800.0
34    플러스 스탠드조명       가구  120500.0
49      베이직 노트북       전자  117200.0
58    플러스 스탠드조명       가구  148400.0
77       데일리 의자      가구   113800.0

In [19]:
# 100000 이상이 몇 개?
expensive.shape[0]     # tuple

20

In [26]:
# 부산에 사는 고객 수
customers_df = pd.read_csv("../data/customers.csv")
customers_df.head()

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [32]:
busan_customers = customers_df.loc[
    customers_df["city"] == "부산", # 행 조건
    ["name", "city"]
]

In [33]:
busan_customers.head()

   name city
18  강태재   부산
37  홍재영   부산
41  박지진   부산
45  홍진준   부산
60  윤진아   부산

In [ ]:
busan_customers.shape[0]    # shape[0] : 행 개수

484