In [1]:
import pandas as pd

products_df = pd.read_csv("../data/products.csv")

In [2]:
products_df.head()

   product_id product_name category    price     cost
0         119       플러스 홍차       식품        0   3700.0
1          95     프리미엄 노트북       전자  68600.0  28900.0
2         112    프리미엄 원두커피       식품  10500.0   4700.0
3         164      베이직 마우스       전자  52100.0  32600.0
4         274       베이직 홍차      식품   16000.0  10500.0

In [ ]:
# 원가가 높은 상품의 이름과 카테고리 추출, cost > 100000 이상
products_df["cost"] > 100000    # Boolean (True, False) return Series

0      False
1      False
2      False
3      False
4      False
       ...
495     True
496    False
497    False
498    False
499    False
Name: cost, Length: 500, dtype: bool

In [ ]:
expensive = products_df.loc[
    products_df['cost'] > 100000,           # 행 자리
    ["product_name", "category", "cost"]    # 열 자리, 다중 열 선택 => 데이터프레임 추출
]
expensive

    product_name category      cost
16        베이직 책상       가구  104800.0
34     플러스 스탠드조명       가구  120500.0
49       베이직 노트북       전자  117200.0
58     플러스 스탠드조명       가구  148400.0
77        데일리 의자      가구   113800.0
133     프리미엄 스피커      전자   119100.0
140    데일리 침대프레임       가구  118800.0
152       베이직 선반       가구  106700.0
186      프리미엄 의자       가구  106900.0
211       베이직 소파       가구  120500.0
260       베이직 선반       가구  165500.0
269      스탠다드 소파       가구  126000.0
277       베이직 의자       가구  111600.0
321       플러스 소파      가구   143200.0
324      코어 마우스        전자  110100.0
397    플러스 스탠드조명       가구  125700.0
400   스탠다드 스탠드조명       가구  114200.0
434       데일리 선반      가구   120200.0
444    플러스 스탠드조명       가구  109100.0
495       베이직 선반       가구  130700.0