In [1]:
import pandas as pd

customers_df = pd.read_csv("../data/customers.csv")

In [ ]:
# 고객번호 중복 확인
# customers_df["customer_id"].duplicated()      # 중복 여부(True / False)
customers_df["customer_id"].duplicated().sum()  # True & False 는 sum()이 됨. True의 개수

np.int64(50)

In [6]:
# 중복된 고객 정보 추출
dup_cust = customers_df.loc[
    customers_df["customer_id"].duplicated(),   # 중복된 행만 선택
    ["customer_id", "name"]
]
dup_cust

      customer_id name
795          3002  윤선우
827          1683  홍준예
1092         5741  임은민
1420         1389  최도은
1525         2682  김현지
1655         1438  이도아
2174         3018  권성은
2211         3136  한예성
2218         1704  박우연
2407         2675  홍성선
2436         1975  정지우
2505         2856  윤도민
2514         2768  이현수
2657         5700  송준우
2754         5290  이준민
2851         5088  홍태연
2868         5747  강지경
2983         4104  권영준
3080         3160  안민예
3137         3745  장재아
3173         3353  임우우
3222         2010  강현수
3226         3259  홍경아
3274         5840  황우도
3405         1316  권성진
3677         1390  권은은
3736         5190  장성태
3750         1870  임수서
3804         2106  정민도
3828         1782  박선영
3893         5512  박예수
3914         5541  서민우
3927         3547  오은지
4029         2300  황영태
4083         5430  전민서
4134         2454  오선태
4147         5106  박선현
4153         5295  홍수은
4159         1310  신태우
4237         3558  김수도
4256         3076  임우성
4367         2516  임하연
4470         3166  조성준
4529         5790  최은재
4605         3558  김수도
4726         1359  권도태
4747         5616  강우아
4797         2230  안하연
4838         3603  오재우
4888         3416  서재준

In [7]:
# customer_id 컬럼을 index로 변환
customers_by_id = customers_df.set_index("customer_id")
customers_by_id.head()

            name gender  birth_date signup_date city                 email
customer_id
3293         권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1862         박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
4955         전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
4653         한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
3331         송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [10]:
restored = customers_by_id.reset_index()
restored.head()

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [16]:
products_df = pd.read_csv("../data/products.csv")
products_by_id = products_df.set_index("product_id")
products_by_id

           product_name category     price      cost
product_id
119              플러스 홍차       식품         0    3700.0
95             프리미엄 노트북       전자   68600.0   28900.0
112           프리미엄 원두커피       식품   10500.0    4700.0
164             베이직 마우스       전자   52100.0   32600.0
274              베이직 홍차      식품    16000.0   10500.0
...                 ...      ...       ...       ...
385              베이직 선반       가구  205900.0  130700.0
492              데일리 시집       도서   19600.0   14200.0
115         프리미엄 스킨케어세트       뷰티   33600.0   14500.0
346               코어 샴푸       뷰티   40500.0   17900.0
478          베이직 스킨케어세트       뷰티   35000.0   20200.0

[500 rows x 4 columns]

In [ ]:
# 95번 상품 추출
products_by_id.loc[95]      # 결과 타입은 Series. 컬럼명이 index, 값이 values
# products_by_id.loc[95]["category"]

product_name    프리미엄 노트북
category              전자
price            68600.0
cost             28900.0
Name: 95, dtype: object