In [2]:
import pandas as pd

In [39]:
customers_df = pd.read_csv("../data/customers.csv")
products_df = pd.read_csv("../data/products.csv")

In [ ]:
# 특정 고객 번호(5000~5010) 범위의 이름, 도시 추출
sel = customers_df.loc[
    customers_df["customer_id"].between(5000, 5010),
    ["customer_id","name", "city"]
].sort_values("customer_id")
sel

      customer_id name city
4994         5000  조지태   서울
4480         5001  안영진   세종
2520         5002  김하재  서울
2955         5003  장성태   고양
4945         5004  안아하   세종
3482         5005  홍우지   부산
4302         5006  강수아   고양
3186         5007  신선수   서울
3249         5008  최예예   수원
1412         5009  박태재   대전
4981         5010  윤예민   서울

In [ ]:
# 서울, 부산에 있는 고객 추출

customers_df.loc[
    customers_df["city"].isin(["서울", "부산"]),
    ["customer_id", "name", "city"]
]

      customer_id name city
1            1862  박준선   서울
3            4653  한재하   서울
8            5090  권재현   서울
10           5055  윤수현   서울
16           3699  박재태   서울
...           ...  ...  ...
4986         1735  신예경   부산
4988         4920  전민예   서울
4991         3750  정성하   서울
4994         5000  조지태   서울
4995         5672  정우은   서울

[1447 rows x 3 columns]

In [ ]:
# 서울, 부산에 있는 고객 외 추출
customers_df.loc[
    ~customers_df["city"].isin(["서울", "부산"]),
    ["customer_id", "name", "city"]
]
# 위 아래 동일
customers_df[~customers_df['city'].isin(["서울", "부산"])][["name", "city"]]

     name city
0     권준서   부산
2     전영경   인천
4     송준연   대전
5     최현우   고양
6     전선태   광주
...   ...  ...
4993  최하수   대구
4996  이예재   고양
4997  조아준   인천
4998  장성우  대전
4999  이하민   수원

[3553 rows x 2 columns]

In [33]:
# 홍차가 포함된 상품명 조회
# products_df["product_name"].str.contains("홍차")
products_df.loc[
    products_df["product_name"].str.contains("홍차"),
    ["product_name","category"]
]

    product_name category
0         플러스 홍차       식품
4         베이직 홍차      식품
7        프리미엄 홍차       식품
65        데일리 홍차       식품
73        데일리 홍차       식품
96       스탠다드 홍차       식품
156      스탠다드 홍차       식품
175        코어 홍차       식품
189        코어 홍차       식품
295       플러스 홍차       식품
306       플러스 홍차       식품
336       베이직 홍차       식품
339       베이직 홍차       식품
350      데일리 홍차        식품
398      스탠다드 홍차       식품
419      스탠다드 홍차       식품
484      스탠다드 홍차       식품

In [42]:
# 성별이 '여'이고 서울 거주하는 고객 추출
condition = (customers_df["gender"] == "여") & (customers_df["city"] == "서울")
# ((customers_df["gender"] == "여") & (customers_df["city"] == "서울")).sum()
customers_df.loc[
    condition,
    ["name","gender","city"]
]

     name gender city
39    신현은      여   서울
58    박연하      여   서울
70    조예아      여   서울
93    황지예      여   서울
103   장수아      여   서울
...   ...    ...  ...
4914  황현재      여   서울
4970  홍태민      여   서울
4974  최은성      여   서울
4981  윤예민      여   서울
4988  전민예      여   서울

[228 rows x 3 columns]

In [ ]:
# 성별 "여"이고 "서울" 거주하는 고객 추출 (잘 씀.)
customers_df.query("gender=='여' and city=='서울'")[["name", "gender","city"]]

     name gender city
39    신현은      여   서울
58    박연하      여   서울
70    조예아      여   서울
93    황지예      여   서울
103   장수아      여   서울
...   ...    ...  ...
4914  황현재      여   서울
4970  홍태민      여   서울
4974  최은성      여   서울
4981  윤예민      여   서울
4988  전민예      여   서울

[228 rows x 3 columns]

In [ ]:
# 원가 상위 5개 추출
# products_df.sort_values("cost", ascending=False).head(5)
products_df.nlargest(5, "cost")

# 원가 하위 5개 추출
products_df.nsmallest(5, "cost")

     product_id product_name category   price    cost
443           4       코어 만화책       도서   1000원   400.0
121         296       플러스 잡지      도서   1000.0   600.0
293         441     플러스 마스크팩       뷰티  1000.0   700.0
7           193      프리미엄 홍차       식품  2200.0   900.0
438         209    프리미엄 장편소설       도서  1700.0  1200.0