In [2]:
# DataFrame을 dict로 직접 생성
import pandas as pd

sample = {
    "product_name":["코어 티셔츠","베이직 노트북","데일리 원두커피"],    # key,value 한 쌍이 Series가 됨. key가 컬럼명, vaule가 값
    "category":["의류","전자","식품"],
    "price":[39000,89000,15000],
}     # Series 모여 DataFrame 됨.

# print(type(sample))
# sample_df = pd.DataFrame()    # 빈 DataFrame 생성
sample_df = pd.DataFrame(sample)    # 빈 DataFrame 생성
sample_df.head()

  product_name category  price
0       코어 티셔츠       의류  39000
1      베이직 노트북       전자  89000
2     데일리 원두커피       식품  15000

In [6]:
# 인덱스 추출
# sample_df.index ; ndarray(다차원배열, numpy) => list로 변환.
# Index : RangeIndex(start=0, stop=3, step=1)
# tolist() : 리스트로 변환
print(f"Index : {sample_df.index.tolist()}")
# Index : [0, 1, 2]

Index : [0, 1, 2]

In [ ]:
# 컬럼 정보 추출
# sample_df.columns 변수 => 레퍼런스 => 오브젝트
sample_df.columns.tolist()

str

In [ ]:
# 데이터프레임(sample_df)의 데이터 타입 추출
sample_df.dtypes     # column마다 dtype
type(sample_df.dtypes)
sample_df.dtypes.index
sample_df.dtypes.values

array([<StringDtype(na_value=nan)>, <StringDtype(na_value=nan)>,
       dtype('int64')], dtype=object)

In [ ]:
# 고객 데이터에서 city 컬럼 꺼내서 정보 확인
customers_df = pd.read_csv("../data/customers.csv")
customers_df.head(3)

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com

In [ ]:
# 데이터프레임에서 컬럼 추출
# city = customers_df["컬럼명"]
city = customers_df["city"]    # city는 Series
city.head(3)    # Series의 head() 메소드

0     부산
1     서울
2     인천
Name: city, dtype: str

In [ ]:
# name 접근
print(type(city).__name__)    # __name__
print(type(city))  # pandas(모듈).Series(클래스)

Series
<class 'pandas.Series'>

In [20]:
# 데이터 타입 확인
city.dtype