In [ ]:
# 데이터 훑어보기 : head(), info(), describe(), value_counts()
# 1. info
import pandas as pd

orders = pd.read_csv(
    "../data/orders.csv",
    parse_dates=["order_datetime"]
)
# orders.head(3)    # 앞에서 3개
# orders.tail(3)    # 뒤에서 3개

        order_id  customer_id      order_datetime channel     status
199997     88502         3265 2024-01-20 06:44:00     app  delivered
199998     62264         2403 2024-03-21 00:22:40     web  delivered
199999      1963         3439 2024-01-01 00:58:02     app   canceled

In [ ]:
# 데이터프레임의 정보 추출
orders.info()
# RangeIndex VS Index : 연속적 VS 비연속적.

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [10]:
# 2. describe() : 기본 통계량(합, 평균, 최대, 최소, 사분위, 표준편차(분산)) 구한다.
order_items_df = pd.read_csv("../data/order_items.csv")
order_items_df.head(3)

   order_item_id  order_id  product_id  quantity  unit_price  discount
0          59256    114625           3         1     20300.0      0.05
1         230587     66337          80         2     90000.0      0.45
2         279813    163343           3         3     20300.0      0.23

In [ ]:
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  500000 non-null  int64
 1   order_id       500000 non-null  int64
 2   product_id     500000 non-null  int64
 3   quantity       500000 non-null  int64
 4   unit_price     484887 non-null  float64
 5   discount       500000 non-null  float64
dtypes: float64(2), int64(4)
memory usage: 22.9 MB

In [21]:
order_items_df["quantity"]    # quantity 단일 컬럼 추출. return Series
order_items_df[["quantity","unit_price","discount"]].describe()# 다중컬럼 추출. 다중컬럼은 return DataFrame

            quantity     unit_price       discount
count  500000.000000  484887.000000  500000.000000
mean        2.997008   50925.557707       0.249688
std         1.418193   48908.412198       0.144496
min        -2.000000    1000.000000       0.000000
25%         2.000000   15100.000000       0.120000
50%         3.000000   27000.000000       0.250000
75%         4.000000   73700.000000       0.370000
max         5.000000  291000.000000       0.500000

In [ ]:
# 3. value_counts() : 값의 개수 확인. Series에서만 사용 가능. (DataFrame은 안 됨.)
# 상품에서 카테고리별 개수
products_df = pd.read_csv("../data/products.csv")
# products_df.head(3)
# products_df.info()
# products_df.describe()
# products_df["category"].value_counts()

category
도서     90
전자     79
식품     75
가구     71
의류     70
뷰티     68
전자     13
가구      9
의류      9
도서      7
뷰티      5
식품      4
Name: count, dtype: int64

In [ ]:
# ['식품', '전자', '식품 ', '의류', '뷰티', '가구', '가구 ', '뷰티 ', '전자 ', '도서', '의류 ', '도서 ']
print(products_df["category"].unique())   # 중복 제거
# 개수
print(products_df["category"].nunique())

<ArrowStringArray>
['식품', '전자', '식품 ', '의류', '뷰티', '가구', '가구 ', '뷰티 ', '전자 ', '도서', '의류 ', '도서 ']
Length: 12, dtype: str
<class 'int'>

In [32]:
# 결측치(누락되어 있는 값) 처리
# 결측 개수
# 고객 데이터
customers_df = pd.read_csv("../data/customers.csv")
customers_df.head()

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [33]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5000 non-null   int64
 1   name         5000 non-null   str
 2   gender       4696 non-null   str
 3   birth_date   4616 non-null   str
 4   signup_date  5000 non-null   str
 5   city         5000 non-null   str
 6   email        4752 non-null   str
dtypes: int64(1), str(6)
memory usage: 544.3 KB

In [ ]:
# 생일 데이터 없는 고객의 수
# isna() : Null이니? Null이면 True, 아니면 False(있으면 True, 없으면 False)
customers_df["birth_date"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: birth_date, Length: 5000, dtype: bool

In [ ]:
# 단일 컬럼의 결측 개수
customers_df["birth_date"].isna().sum()    # True: 1, False : 0

np.int64(384)

In [48]:
# 전체 컬럼 각각의 결측 개수 -> Series
customers_df.isna().sum()[["email","gender"]]

email     248
gender    304
dtype: int64